name: stale update

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-stale:
    runs-on: ubuntu-latest
    steps:
      - issues: Checkout repository
        uses: actions/checkout@v2

      - issues: Update stale issues and pull requests
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been marked as stale due to inactivity. It will be closed if no further activity occurs.'
          stale-pr-message: 'This pull request has been marked as stale due to inactivity. It will be closed if no further activity occurs.'
          days-before-stale: 30
          days-before-close: 7
          exempt-labels: 'pinned,important'